#!/bin/sh
#
# fluxbox startup-script:
#
# Lines starting with a '#' are ignored.

# Change your keymap:
xmodmap "/home/akts/.Xmodmap"


# Applications you want to run with fluxbox.
# MAKE SURE THAT APPS THAT KEEP RUNNING HAVE AN ''&'' AT THE END.
#
# unclutter -idle 2 &
# wmnd &
# wmsmixer -w &
# idesk &

# Start DBUS session bus:
if [ -z "$DBUS_SESSION_BUS_ADDRESS" ]; then
   eval $(dbus-launch --sh-syntax --exit-with-session)
fi

# And last but not least we start fluxbox.
# Because it is the last app you have to run it with ''exec'' before it.

#exec fluxbox

xset b off &
setxkbmap -option caps:escape &
xset r rate 350 50 &
~/.fehbg &

# x fonts
xset +fp ~/.fonts/ohsnap
xset +fp ~/.fonts/tamzen-font/bdf
xset +fp ~/.fonts/fixed-dotted-zero
xset fp rehash

# touch pad -- start
synclient VertEdgeScroll=1 HorizEdgeScroll=1 TapButton1=1 2>/dev/null
## alternative:
#synclient VertEdgeScroll=0 VertTwoFingerScroll=0 HorizEdgeScroll=0 TapButton1=1 TapButton2=3 TapButton3=2 PalmDetect=1 PalmMinWidth=4 PalmMinZ=100

## Disable touchpad while typing
syndaemon -i .5 -K -t -R -d &

# touchpad -- end

# see ~/.xinitrc
/usr/lib64/xfce4/notifyd/xfce4-notifyd &
/usr/libexec/polkit-gnome-authentication-agent-1 &
xbacklight -set 55 &
(sleep 1s && nm-applet) &
(sleep 2s && xfce4-power-manager) &
(sleep 1s && cbatticon -x xfce4-power-manager-settings) &
#pnmixer &
start_pulseaudio.sh &
(sleep 1s && volumeicon) &
clipit &
#compton &
#gkrellm -w &
idesk &
(sleep 1s && conky -c $HOME/.config/conky/conkyrc.simple.lua) &

exec fluxbox

# or if you want to keep a log:
# exec fluxbox -log "/home/akts/.fluxbox/log"
